export const skillsArray = [
    {
        name: 'PHP',
        description: 'Web development, Scrapping',
        link: 'https://www.php.net/',
        type: 'development',
        image: '/assets/images/skills/php.png',
    },
    {
        name: 'React',
        description: 'Web development',
        link: 'https://reactjs.org/',
        type: 'development',
        image: '/assets/images/skills/react.png',
    },
    {
        name: 'Python',
        description: 'Web development, scrapping',
        link: 'https://www.python.org/',
        type: 'development',
        image: '/assets/images/skills/python.png',
    },
    {
        name: 'Javascript',
        description: 'Web development',
        link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
        type: 'development',
        image: '/assets/images/skills/javascript.png',
    },
    {
        name: 'Typescript',
        description: 'Web development',
        link: 'https://www.typescriptlang.org/',
        type: 'development',
        image: '/assets/images/skills/typescript.png',
    },
    {
        name: 'Html5',
        description: 'Web layouts',
        link: 'https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5',
        type: 'development',
        image: '/assets/images/skills/html-5.png',
    },
    {
        name: 'Css3',
        description: 'Web design',
        link: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
        type: 'design',
        image: '/assets/images/skills/css3.png',
    },
    {
        name: 'Bootstrap',
        description: 'Web design',
        link: 'https://getbootstrap.com/',
        type: 'design',
        image: '/assets/images/skills/bootstrap.png',
    },
    {
        name: 'Tailwind CSS',
        description: 'Web design',
        link: 'https://tailwindcss.com/',
        type: 'design',
        image: '/assets/images/skills/tailwind.png',
    },
    {
        name: 'MySql',
        description: 'Database',
        link: 'https://www.mysql.com/',
        type: 'database',
        image: '/assets/images/skills/mysql.png',
    },
    {
        name: 'SQLite',
        description: 'Database',
        link: 'https://www.sqlite.org',
        type: 'database',
        image: '/assets/images/skills/sqlite.jpg',
    },
    {
        name: 'Redis',
        description: 'Database',
        link: 'https://redis.io/',
        type: 'database',
        image: '/assets/images/skills/redis.png',
    },
    {
        name: 'Digital Ocean',
        description: 'Devops',
        link: 'https://www.digitalocean.com/',
        type: 'devops',
        image: '/assets/images/skills/digital-ocean.png',
    },
    {
        name: 'Media Temple',
        description: 'Devops',
        link: 'https://mediatemple.net/',
        type: 'devops',
        image: '/assets/images/skills/media-temple.png',
    },
    {
        name: 'Apache',
        description: 'Web server',
        link: 'https://www.apache.org/',
        type: 'devops',
        image: '/assets/images/skills/apache.png',
    },
    {
        name: 'Visual Studio Code',
        description: 'Code editor of choice',
        link: 'https://code.visualstudio.com/',
        type: 'development',
        image: '/assets/images/skills/vscode.png',
    },
    {
        name: 'Adobe Photoshop',
        description: 'Web design',
        link: 'https://www.adobe.com/sea/products/photoshop.html',
        type: 'design',
        image: '/assets/images/skills/photoshop.png',
    }
]